# Lab 2 - *NumPy* Basics

(10 pts)

### Replace the `?`s in the following cells with code to perform the requested task. 

In [2]:
import numpy as np

<u>***Question 1. (pt 1)***</u> :

Convert the following list to a *NumPy* Array.

In [3]:
list_to_convert = [1, 2, 3] 
numpy_array = np.array(list_to_convert)
numpy_array 

array([1, 2, 3])

<u>***Question 2. (pt 1)***</u> :

Create a 3x4 Array of Zeros.

In [5]:
zeros_array_3x4 = np.zeros((3,4))
zeros_array_3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<u>***Question 3. (pt 1)***</u> :

numpy.ones() is a function similar to numpy.zeros we introduced in class. Please read the following reference https://numpy.org/doc/stable/reference/generated/numpy.ones.html


Create a 3x4 Array of Ones.

In [6]:
ones_array_3x4 = np.ones((3,4))
ones_array_3x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<u>***Question 4. (pt 1)***</u> :

Create a 4x3 Empty Array.

In [10]:
empty_array_4x3 = np.empty((4,3))
empty_array_4x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<u>***Question 5. (pt 1)***</u> :

Use a *NumPy* function to create an array with all of the odd numbers between 1 and 10, inclusive.  

In [14]:
odd_vals = np.arange(1, 11, 2) 
odd_vals

array([1, 3, 5, 7, 9])

<u>***Question 6. (pt 1)***</u> :

Use an array method to find the number of rows and columns in `empty_array_4x3`. 

In [15]:
dims = empty_array_4x3.shape
dims

(4, 3)

<u>***Question 7. (pt 1)***</u> :

Use a *NumPy* function to generate a range of values starting at 1 and going to 10, and put these into 5x2 Array.  

In [18]:
vals_5x2 = np.arange(1, 11).reshape(5, 2)
vals_5x2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

<u>***Question 8. (pt 1)***</u> :

Use an array method to determine the data type of values in the `empty_array_4x3` array.

In [19]:
data_type = empty_array_4x3.dtype
data_type

dtype('float64')

<u>***Question 9. (pt 1)***</u> :

Create a 6x3 array of randomly generated normally distributed values. 

In [22]:
random_6x3 = np.random.randn(6, 3)
random_6x3

array([[ 1.43577019, -1.63227181,  0.15428906],
       [ 0.93827169,  1.06482046, -0.77680766],
       [ 0.70052789,  0.69665609, -0.89348464],
       [ 0.58247963, -0.8602002 , -0.27076627],
       [-0.00984755, -1.68081409,  1.74476813],
       [ 0.23779762, -0.62480776,  0.4032153 ]])

<u>***Question 10. (pt 1)***</u> :

Create a 6x3 Boolean array with `True` values for all of the numbers in the `random_6x3` array that are greater than 1. 

In [23]:
greater_than_1 = random_6x3 > 1
greater_than_1

array([[ True, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])